name: CD workflow

on:
  push:
    branches:
      - learn

jobs:
  upload-extension:
    name: Upload updated extension
    runs-on: ubuntu-latest
    # needs: gather-files
    env:
      CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
      CODE: 4/1AfJohXlmJpB03w8Ik42pIRbVz-dlbMm8I3I22HkBSjilW2gsxrmJKdWw8jA
    steps:
      - name: install dependencies
        run: sudo apt-get -y install curl jq

      - name: request access token
        run: |-
          curl "https://accounts.google.com/o/oauth2/token" -d \
            "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&code=4/1AfJohXlmJpB03w8Ik42pIRbVz-dlbMm8I3I22HkBSjilW2gsxrmJKdWw8jA&grant_type=authorization_code&redirect_uri=urn:ietf:wg:oauth:2.0:oob"

      - name: save access token
        run: |-
          RESPONSE=$(curl "https://accounts.google.com/o/oauth2/token" -d \
            "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&code=4/1AfJohXlmJpB03w8Ik42pIRbVz-dlbMm8I3I22HkBSjilW2gsxrmJKdWw8jA&grant_type=authorization_code&redirect_uri=urn:ietf:wg:oauth:2.0:oob"| jq -r '.error_description')
          echo $RESPONSE

      - name: upload updated package
        run: |-
          curl \
            -H "Authorization: Bearer $TOKEN"  \
            -H "x-goog-api-version: 2" \
            -X PUT \
            -T $FILE_NAME \
            -v \
            https://www.googleapis.com/upload/chromewebstore/v1.1/items/$ITEM_ID