name: CD workflow

on:
  push:
    branches:
      - main

jobs:
  upload-extension:
    name: Upload updated extension
    runs-on: ubuntu-latest
    # needs: gather-files
    env:
      CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
      CODE: 4/1AfJohXmaLrn3275ary6BhODqrkKrKjVASs_ljcfx6LRw9r_iU3mfTtEZir4
    steps:
      - name: install dependencies
        run: sudo apt-get -y install curl jq

      - name: request access token
        run: |-
          curl "https://accounts.google.com/o/oauth2/token" -d \
            "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&code=4/1AfJohXlmJpB03w8Ik42pIRbVz-dlbMm8I3I22HkBSjilW2gsxrmJKdWw8jA&grant_type=authorization_code&redirect_uri=urn:ietf:wg:oauth:2.0:oob"

      - name: save access token
        run: |-
          ERROR=$(curl "https://accounts.google.com/o/oauth2/token" -d \
            "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&code=$CODE&grant_type=authorization_code&redirect_uri=urn:ietf:wg:oauth:2.0:oob"| jq -r '.error')
          printf '%s\n' "$ERROR"
          echo "TOKEN=$ERROR" >> "$GITHUB_ENV"

      - name: display $TOKEN
        run: |-
          echo "$TOKEN"