name: Github PR Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      

jobs:
  Check-Version-Number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get list of files changed
        id: changed-files-list
        run: |-
          files_string=$(git diff --name-only -r HEAD^1 HEAD | xargs)
          echo "files=$files_string" >> $GITHUB_OUTPUT

        
      - name: Display result
        run: |
          for file in ${{ steps.changed-files-list.outputs.files }}; do
              echo "$file was changed"
          done
      
      - name: Change string into array
        id: changed-files-array
        run: |
          IFS=' ' read -ra files_array <<< "$files"
          echo "files_array=(${files_array[@]})" >> $GITHUB_OUTPUT
      
      - name: Display array result
        run: |
          echo ${{ steps.changed-files-array.outputs.files_array }}

      - name: Check if pulll-request-check.yml is changed
        uses: actions/github-script@v7
        with:
          script: |
            console.log(typeof ${{ steps.changed-files-array.outputs.files_array}});
