name: Github PR Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      

jobs:
  Check-Version-Number:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            let error = true
            for (let commit of ${{ github.event.commits }}){
              console.log(commit.message)
              console.log(added)
            }